version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      JWT_SECRET: random#secret
      DB_USER: main_admin
      DB_HOST: db
      DB_NAME: restaurant_db
      DB_PASSWORD: Wh1te123
      DB_PORT: 5432
      PORT: 5000
    depends_on:
      - db
    networks:
      - app-network

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: main_admin
      POSTGRES_PASSWORD: Wh1te123
      POSTGRES_DB: restaurant_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  # Измените этот порт для HTTPS
    networks:
      - app-network

  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"  # Добавьте secure entrypoint для HTTPS
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"  # Опция для автоматического обновления SSL сертификатов
    ports:
      - "80:80"
      - "443:443"  # Прокси HTTPS на 443 порт
      - "8081:8080"
    networks:
      - app-network
    depends_on:
      - frontend
      - backend
      - admin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
